#' Apply sampletags to the pData slot of a flowSet
#' @param input A \code{\link[flowCore:flowSet-class]{flowCore::flowSet}} or GatingSet
#' @param exp_info A cytobank experiment info object generated by \code{\link{get_experimentinfo}}
#' @return a tagged flowSet or gatingSet, note that samples will be matched by filename to the FCS.filename slot of the samples tags
#' @importFrom magrittr %>%
#' @importFrom dplyr rename
#' @import tibble
#' @export
#' @rawNamespace import(flowCore, except = filter)

apply_sampletags <- function(input, exp_info, panel = NULL){
  output <- input
  sampletags.i  <- exp_info$sampletags

  pData.i <- sampletags.i[match(rownames(pData(input)), sampletags.i$FCS.Filename),]
  rownames(pData.i) <- rownames(pData(input))

  pData(output) <- pData.i

  return(output)
}
