#' Apply panel names to a flowframe or tibble
#' @param input A \code{\link[flowCore:flowFrame]{flowCore::flowFrame}} or tibble with the original channel names as the shortNames or columns (respectively).
#' @param exp_info A cytobank experiment info object generated by \code{\link{get_experimentinfo}}
#' @param panel A character string specifying the panel to be applied (neccessary if >1 panel present).
#' @return If `input` was a flowFrame, returns a flowFrame with the 'desc' for each channel renamed approriately
#' @return If `input` was a tibble, return a tibble with the columns renamed approriately.
#' @importFrom magrittr %>%
#' @importFrom dplyr rename
#' @import tibble
#' @export
#' @rawNamespace import(flowCore, except = filter)

apply_panel <- function(input, exp_info, panel = NULL){
  #panel <- "Panel 2"
  scales.i <- exp_info$scales
  if(length(scales.i) >1 & is.null(panel)){
    names(scales.i)
    warning(paste0("More than one panel found, please specify `panel =`\n"),
            paste0(paste0("-", names(scales.i)), collapse = "\n"))
    return(NULL)
  } else if(!panel %in% names(scales.i)){
    warning(paste0(panel, " not found. Please elect from:\n",
            paste0(paste0("-", names(scales.i)), collapse = "\n")))
    return(NULL)
  }


  if(is_tibble(input)){
    input.tidy <- input
  }else if(class(input) == "flowFrame"){
    input.tidy <- as_tibble(exprs(input))
  } else {
    input.tidy <- as_tibble(input)
  }

  longName <- as.character(scales.i[[panel]][["scales"]]$longName)
  shortName <- as.character(scales.i[[panel]][["scales"]]$shortName)
  names(shortName) <- longName

  if(is_tibble(input)){
    output.tidy<- input.tidy %>%
      rename(!!!shortName)
    output <- output.tidy
  }else if(class(input) == "flowFrame"){
    output <- input
    markernames.tmp <- names(shortName)
    names(markernames.tmp) <- shortName
    markernames(output) <- markernames.tmp
  } else{
    output <- output.tidy
  }

  return(output)
}
